import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Dela_Gothic_One } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const dela = Dela_Gothic_One({
  subsets:['latin'],
  weight: '400',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
